config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: "salaries#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :salaries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :user
  validates :month, presence: true

  MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
                 'July', 'Aug', 'September', 'Octomber', 'November', 'December']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :email, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :salaries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home

  end
end

app/controllers/salaries_controller.rb
# require 'fusioncharts-rails'
class SalariesController < ApplicationController

  def index
    @salaries = Salary.all

    @monthly_salary = {}
    Salary.where(:user_id => current_user.id).each do |s|
      @monthly_salary[s.month] = s.salary
    end
    @monthly_bonus = {}
    Salary.where(:user_id => current_user.id).each do |s|
      @monthly_bonus[s.month] = s.bonus
    end
  end

  def show
    @salary = Salary.find(params[:id])
  end

  def new
    @salary = Salary.new
  end

  def create
    @salary = Salary.new(salary_params)
    @salary.user = current_user
    if @salary.save
      redirect_to salaries_path
    else
      render :new, stauts: :unprocessable_entity
    end
  end

  def edit
    @salary = Salary.find(params[:id])
  end

  def update
    @salary = Salary.find(params[:id])
    @salary.update(salary_params)
    redirect_to root_path
  end

  def destroy
    @salary = Salary.find(params[:id])
    @salary.destroy
    redirect_to salaries_path, notice: 'Salary was successfully destroyed.', status: :see_other
  end


  private

  def salary_params
    params.require(:salary).permit(:salary, :bonus, :month)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalaryPromobizMd</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  </head>

  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-for-home">
  <h1>Welcome <%= current_user.first_name %><%= current_user.last_name %></h1>
  <%= link_to "See your salary", salaries_path, class: "button-see-salary" %>


</div>

app/views/salaries/edit.html.erb
<div class = "banner-new">
  <div class="container">
    <h1>Edit Your Salary</h1>
    <%= simple_form_for @salary do |f| %>
      <%= f.input :salary %>
      <%= f.input :bonus %>
      <%= f.input :month, collection: Salary::MONTHS %>
      <%= f.submit "Edit Salary", class: 'btn btn-primary text-white' %>
      <%= link_to "Back to Main page", salaries_path, class: 'btn btn-danger text-white', style: 'margin: 10px;'  %>
    <% end %>
  </div>
</div>

app/views/salaries/index.html.erb
<% if user_signed_in? %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn2.editmysite.com/images/editor/theme-background/stock/Mountain-Backpacking.jpg);">
    <div class="container-banner">
      <h1>Bun Venit <br> <strong><%= current_user.first_name  %></strong> <strong><%= current_user.last_name  %></strong></h1>
      <p>Aici poti analiza salariul si bonusul primit in perioada curenta (<%= Date.current.year %>)</p>
      <%= link_to "Adauga Un Salariu", new_salary_path, id: "salary-button" %>
    </div>
  </div>
  <div class="container-for-index">
        <div class="add-sallary-container">
        </div>
        <div class="charts">
        <div class="chart-1">
        <h3>Salariul Lunar</h3>
            <%= column_chart(@monthly_salary,
                            colors: ["#b00", "#666"],
                            xtitle: "Luna", ytitle: "Lei MDL") %>
        </div>
        <div class="chart-2">
          <h3>Bonusul Lunar</h3>
            <%= column_chart(@monthly_bonus,
                             xtitle: "Luna", ytitle: "Lei MDL")  %>
        </div>
      </div>

  <% else %>
        <h1>Please Sign In/Sign Up to see your income</h1>
        <%= link_to "Sign In", user_session_path %>
  </div>
<% end %>

app/views/salaries/new.html.erb
<div class = "banner-new" style='background-image: url(https://cdn2.editmysite.com/images/editor/theme-background/stock/Mountain-Backpacking.jpg)'>
  <div class="container-salary-new">
    <h1>Adauga-ti Salariul</h1>
    <div class="salary-new">
      <%= simple_form_for @salary do |f| %>
        <%= f.input :salary,
              label: false,
              placeholder: "Salariul Primit" %>
        <%= f.input :bonus,
                    label: false,
                    placeholder: "Bonusul Primit" %>
        <%= f.input :month, collection: Salary::MONTHS %>
        <%= f.submit "Submit Salary", id: 'submit-salary' %>
        <div class="line"></div>
        <%= link_to "Back to Main page", salaries_path, id: 'back-to-main'  %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://www.promobiz.md/uploads/1/3/0/0/130050179/logo-promobiz-google_orig.png", class: "logo" %>
    <% end %>

    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>

    <div class="navbar-nav" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
             <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>